server:
  port: 8081
spring:
  application:
    name: match-eninge
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 指定使用 Druid 连接池
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/match_engine?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root123

    # Druid 连接池配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
#      filters: stat,wall,log4j  # 配置监控统计拦截的filters，stat:监控统计、log4j:日志记录、wall:防御SQL注入
      web-stat-filter: # WebStatFilter配置
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet: # StatViewServlet配置
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        # deny: 192.168.1.100

  kafka:
      topic: ${spring.kafka.topic}
      bootstrap-servers: localhost:9092  # Kafka 服务器地址
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
        group-id: my-group  # 消费者组 ID
        auto-offset-reset: earliest  # 消费位置重置策略
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        max-poll-records: 100  # 每次拉取的最大记录数
        properties:
          fetch.max.wait.ms: 500  # 最大等待时间

# application.yml
logging:
  level:
    root: INFO  # 根日志级别
    com.github.krystalics: DEBUG  # 自定义包的日志级别、debug级别时能看到mybatis执行的sql
    org.springframework: WARN  # Spring 框架的日志级别
    org.mybatis: DEBUG #mybatis的日志debug、查看运行的sql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

